In [5]:
!pip3 install pandas
import pandas as pd

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Requirement already satisfied: pandas in /opt/homebrew/lib/python3.9/site-packages (1.3.4)
Requirement already satisfied: python-dateutil>=2.7.3 in /opt/homebrew/lib/python3.9/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /opt/homebrew/lib/python3.9/site-packages (from pandas) (2021.3)
Requirement already satisfied: numpy>=1.20.0 in /opt/homebrew/lib/python3.9/site-packages (from pandas) (1.21.4)
Requirement already satisfied: six>=1.5 in /opt/homebrew/lib/python3.9/site-packages (from python-dateutil>=2.7.3->pandas) (1.16.0)
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621

In [6]:
full_data = pd.read_csv('cannabis.csv')
full_data

,Strain,Type,Rating,Effects,Flavor,Description
0,100-Og,hybrid,4.0,"Creative,Energetic,Tingly,Euphoric,Relaxed","Earthy,Sweet,Citrus",$100 OG is a 50/50 hybrid strain that packs a ...
1,98-White-Widow,hybrid,4.7,"Relaxed,Aroused,Creative,Happy,Energetic","Flowery,Violet,Diesel",The ‘98 Aloha White Widow is an especially pot...
2,1024,sativa,4.4,"Uplifted,Happy,Relaxed,Energetic,Creative","Spicy/Herbal,Sage,Woody",1024 is a sativa-dominant hybrid bred in Spain...
3,13-Dawgs,hybrid,4.2,"Tingly,Creative,Hungry,Relaxed,Uplifted","Apricot,Citrus,Grapefruit",13 Dawgs is a hybrid of G13 and Chemdawg genet...
4,24K-Gold,hybrid,4.6,"Happy,Relaxed,Euphoric,Uplifted,Talkative","Citrus,Earthy,Orange","Also known as Kosher Tangie, 24k Gold is a 60%..."
...,...,...,...,...,...,...
2346,Zeus-Og,hybrid,4.7,"Happy,Uplifted,Relaxed,Euphoric,Energetic","Earthy,Woody,Pine",Zeus OG is a hybrid cross between Pineapple OG...
2347,Zkittlez,indica,4.6,"Relaxed,Happy,Euphoric,Uplifted,Sleepy","Sweet,Berry,Grape",Zkittlez is an indica-dominant mix of Grape Ap...
2348,Zombie-Kush,indica,5.0,"Relaxed,Sleepy,Talkative,Euphoric,Happy","Earthy,Sweet,Spicy/Herbal",Zombie Kush by Ripper Seeds comes from two dif...
2349,Zombie-Og,indica,4.4,"Relaxed,Sleepy,Euphoric,Happy,Hungry","Sweet,Earthy,Pungent",If you’re looking to transform into a flesh-ea...
2350,Zoom-Pie,indica,4.6,"Hungry,Relaxed,Uplifted,Happy,Sleepy","Berry,Earthy,Pungent",Zoom Pie (also known as Zombie Pie) is a heavy...

In [7]:
strain_data = full_data.drop(columns=['Type', 'Effects', 'Flavor'])

In [8]:
flavor_list =[]
for i, flavors in enumerate(full_data.get('Flavor')):
        flavorArr = str(flavors).split(',')
        for flavor in flavorArr:
            flavor_list.append([flavor, i])
            
flavor_list = pd.DataFrame(flavor_list, columns=['Flavor', 'Strain_ID'])
flavor_list.Flavor = flavor_list.Flavor.astype('string')

flavor_data = pd.Series(full_data['Flavor'].str.get_dummies(sep=',').columns, dtype='string')

flavor_xref = []
for index, flavor in flavor_data.items():
    
    for flav, strain_id in flavor_list.values:
        if flav == flavor:
            flavor_xref.append([index, strain_id])
            
flavor_xref = pd.DataFrame(flavor_xref, columns=['Flavor_id', 'Strain_id'])

In [9]:
effect_list =[]
for i, effects in enumerate(full_data.get('Effects')):
        effectArr = str(effects).split(',')
        for effect in effectArr:
            effect_list.append([effect, i])
            
effect_list = pd.DataFrame(effect_list, columns=['Effects', 'Strain_ID'])
effect_list.Effects = effect_list.Effects.astype('string')

effect_data = pd.Series(full_data['Effects'].str.get_dummies(sep=',').columns, dtype='string')

effect_xref = []
for index, effect in effect_data.items():
    
    for flav, strain_id in effect_list.values:
        if flav == effect:
            effect_xref.append([index, strain_id])
            
effect_xref = pd.DataFrame(effect_xref, columns=['Effect_id', 'Strain_id'])

In [10]:
type_list =[]
for i, types in enumerate(full_data.get('Type')):
        typeArr = str(types).split(',')
        for type in typeArr:
            type_list.append([type, i])
            
type_list = pd.DataFrame(type_list, columns=['Type', 'Strain_ID'])
type_list.Type = type_list.Type.astype('string')

type_data = pd.Series(full_data['Type'].str.get_dummies(sep=',').columns, dtype='string')

type_xref = []
for index, type in type_data.items():
    
    for flav, strain_id in type_list.values:
        if flav == type:
            type_xref.append([index, strain_id])
            
type_xref = pd.DataFrame(type_xref, columns=['Type_id', 'Strain_id'])

In [11]:
flavor_data

0          Ammonia
1            Apple
2          Apricot
3            Berry
4             Blue
5        Blueberry
6           Butter
7           Cheese
8         Chemical
9         Chestnut
10          Citrus
11          Coffee
12          Diesel
13          Earthy
14         Flowery
15           Fruit
16           Grape
17      Grapefruit
18           Honey
19        Lavender
20           Lemon
21            Lime
22           Mango
23         Menthol
24            Mint
25           Minty
26            None
27           Nutty
28          Orange
29           Peach
30            Pear
31          Pepper
32            Pine
33       Pineapple
34            Plum
35         Pungent
36            Rose
37            Sage
38           Skunk
39    Spicy/Herbal
40      Strawberry
41           Sweet
42             Tar
43             Tea
44         Tobacco
45            Tree
46        Tropical
47         Vanilla
48          Violet
49           Woody
dtype: string

In [12]:
flavor_xref

      Flavor_id  Strain_id
0             0        124
1             0        136
2             0        390
3             0        468
4             0        478
...         ...        ...
6621         49       2315
6622         49       2333
6623         49       2335
6624         49       2337
6625         49       2346

[6626 rows x 2 columns]

In [13]:
effect_data

0       Aroused
1      Creative
2           Dry
3     Energetic
4      Euphoric
5       Focused
6        Giggly
7         Happy
8        Hungry
9         Mouth
10         None
11      Relaxed
12       Sleepy
13    Talkative
14       Tingly
15     Uplifted
dtype: string

In [14]:
effect_xref

       Effect_id  Strain_id
0              0          1
1              0         12
2              0         37
3              0         41
4              0         47
...          ...        ...
11231         15       2344
11232         15       2345
11233         15       2346
11234         15       2347
11235         15       2350

[11236 rows x 2 columns]

In [15]:
type_data

0    hybrid
1    indica
2    sativa
dtype: string

In [16]:
type_xref

      Type_id  Strain_id
0           0          0
1           0          1
2           0          3
3           0          4
4           0          6
...       ...        ...
2346        2       2334
2347        2       2335
2348        2       2342
2349        2       2343
2350        2       2345

[2351 rows x 2 columns]

In [17]:
strain_data

,Strain,Rating,Description
0,100-Og,4.0,$100 OG is a 50/50 hybrid strain that packs a ...
1,98-White-Widow,4.7,The ‘98 Aloha White Widow is an especially pot...
2,1024,4.4,1024 is a sativa-dominant hybrid bred in Spain...
3,13-Dawgs,4.2,13 Dawgs is a hybrid of G13 and Chemdawg genet...
4,24K-Gold,4.6,"Also known as Kosher Tangie, 24k Gold is a 60%..."
...,...,...,...
2346,Zeus-Og,4.7,Zeus OG is a hybrid cross between Pineapple OG...
2347,Zkittlez,4.6,Zkittlez is an indica-dominant mix of Grape Ap...
2348,Zombie-Kush,5.0,Zombie Kush by Ripper Seeds comes from two dif...
2349,Zombie-Og,4.4,If you’re looking to transform into a flesh-ea...
2350,Zoom-Pie,4.6,Zoom Pie (also known as Zombie Pie) is a heavy...

In [22]:
flavor_data.to_csv('flavor_data.csv', header=True)
flavor_xref.to_csv('flavor_xref.csv', header=True)
effect_data.to_csv('effect_data.csv', header=True)
effect_xref.to_csv('effect_xref.csv', header=True)
type_data.to_csv('type_data.csv', header=True)
type_xref.to_csv('type_xref.csv', header=True)
strain_data.to_csv('strain_data.csv', header=True)